### ISSUE TITLE
Question: Do we need to follow the instructions for setting up XC Server as a Service?

### ISSUE THREAD

**Issue by rh535** [groenator/iptvboss-docker#22]
I'm trying to get the XC server working and was wondering if we need to set up: Setting up IPTVBoss XC Server as a Service - in the guide?

If so, what is the sudo password for the first step in the Linux instructions?

Thanks

**Comment by groenator** [comment]
What issues are you experiencing? The guide is straight forward. When you set the `XC_SERVER="true"` the server will start on boot. This is a docker container not a VM, root is not available inside the container. The user is all set up by declaring the correct uid and gid inside the envs.

Follow: https://github.com/groenator/iptvboss-docker?tab=readme-ov-file#docker-compose-preferred-way

**Comment by groenator** [comment]
Can you share some logs and your configuration? This shouldn't happen, all of this is automated to start even 8f you reboot the container.

**Comment by groenator** [comment]
Hi, 

I wonder what are the permissions set for your local folder where you are storing the IPTVBoss data. 

I see that you are starting the container with user 1000, which is good because you dont need to use root. However, check the permissions on the folder that you mounted inside the container, which is `/mnt/user/appdata/iptvboss/`. 

You should have the perms set to user 1000:1000 as well. I pasted your errors in ChatGPT and the first thing which was mention was permissions. 

The container is configure to start everything on boot, you shouldn't have to go inside the terminal start xcserver manually. I making a point and not critisinging you :)

**Comment by groenator** [comment]
> I believe it was related to a database issue that stemmed from a source. Thanks again for the help!

:+1:
