### ISSUE TITLE
'Light-Locker' (libglib) causing kernel traps

### ISSUE THREAD

**Issue by GOvEy1nw** [groenator/iptvboss-docker#34]
Hey, I've been getting the following error on my Unraid server recently, and I've only just figured out that it's coming from the IPTVBoss docker container:

`Sep 13 13:58:53 Tower kernel: traps: light-locker[2628] trap int3 ip:1465f240eca7 sp:7ffe1d561970 error:0 in libglib-2.0.so.0.6600.8[1465f23d2000+89000]`

Could you please take a look at fixing this please?

**Comment by GOvEy1nw** [comment]
Just an update on this. I figured I'd try something, and ran 'sudo apt purge light-locker' inside the container to uninstall it. That change currently survived a restart of the container too, and it still seems to run without issue. So it'd be great if you could add that command to the entrypoint script.

**Comment by groenator** [comment]
I checked the Unraid community and it seems there's an issue with unraid kernel. 

https://forums.unraid.net/topic/134073-uraid-keep-crashing/

Have you tried discussing it with unraid community first?

**Comment by GOvEy1nw** [comment]
I discovered the error when checking unraid syslogs one day. That specific package 'libglib-2.0.so.0.6600.8' isn't installed in Unraids system, at least not now as that thread is over 1.5yrs old and they've since updated libglib, but even then Unraid doesn't use or have 'Light-Locker' installed at all as it isn't a GUI system.

I have discussed it in the unraid community, and also exhaustively browsed all other threads listed in unraid forums with pertaining to specifically 'libglib-2.0.so.0.6600.8' and just 'libglib'. The outcome was that the last time someone had an issue with that package was in June 2023, and it was due to a docker container.

Prior to me just removing light-locker from the IPTVBoss container just now, I hadn't installed any other packages or changed the container at all in any way.

**Comment by groenator** [comment]
Hi,

I'm concerned that removing this package might interfere with the Boss or VNC packages, potentially breaking the container.

Unfortunately, I can't simply remove the package because one system relies on it, and I'm not certain that the Boss container is the actual cause. My recommendation would be to rebuild a new Docker image and remove the package yourself. You could also add an entrypoint in the docker-compose file to uninstall the package. This would likely be easier than rebuilding the entire image.

It's important to note that the libglib package is a library used by the glibc package, which is essential to the system. glibc (GNU C Library) is a core component in Linux systems, providing basic functions like memory allocation and I/O operations. Removing it would disrupt the entire container, as many other packages depend on it to function properly.

**Comment by GOvEy1nw** [comment]
Yea that's fine, I only removed 'Light-Locker', not the full libglib package. I can spin off my own fork and remove it for myself anyway. Seems to be working fine without it. Will report back at a later date if that changes.

**Comment by groenator** [comment]
Hi, 

Please do an let me know. 

It looks like this package is part of the Desktop: https://github.com/the-cavalry/light-locker

Regards,

**Comment by groenator** [comment]
Maybe is best to raise an issue with them too, ask them why are you getting this traps when their package is installed on unraid.
